spring:
  application:
    name: springboot-crud-funcionario-java
    description: Projeto tem o objetivo de efetuar um CRUD de funcionário
  server:
    address: 0.0.0.0
    port: 8080
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
    console:
      path: /h2-ui
  profile:
    active: local
